const dictionary = {
    "Libro - Lección 1": {
        words: [
            { hanzi: "你", pinyin: "nǐ", meaning: "tú" },
            { hanzi: "好", pinyin: "hǎo", meaning: "bien, bueno, OK" },
            { hanzi: "吗", pinyin: "ma", meaning: "partícula interrogativa (sí/no)" },
            { hanzi: "我", pinyin: "wǒ", meaning: "yo, mi, me" },
            { hanzi: "很", pinyin: "hěn", meaning: "muy" },
            { hanzi: "呢", pinyin: "ne", meaning: "partícula modal" },
            { hanzi: "也", pinyin: "yě", meaning: "también, además" },
            { hanzi: "陆雨平", pinyin: "Lù Yǔpíng", meaning: "(Nombre)" },
            { hanzi: "力波", pinyin: "Lìbō", meaning: "(Nombre)" },
            { hanzi: "林娜", pinyin: "Lín Nà", meaning: "(Nombre)" }
        ],
        sentences: [
            { hanzi: "你好", pinyin: "nǐ hǎo", meaning: "Hola" },
            { hanzi: "你好吗", pinyin: "nǐ hǎo ma", meaning: "¿Cómo estás?" },
            { hanzi: "我很好", pinyin: "wǒ hěn hǎo", meaning: "Estoy muy bien" },
            { hanzi: "你也很好", pinyin: "wǒ yě hěn hǎo", meaning: "Yo también estoy muy bien" }
        ]
    },
    "Libro - Lección 2": {
        words: [
            { hanzi: "忙", pinyin: "máng", meaning: "ocupado" },
            { hanzi: "爸爸", pinyin: "bàba", meaning: "padre" },
            { hanzi: "妈妈", pinyin: "māma", meaning: "madre" },
            { hanzi: "他们", pinyin: "tāmen", meaning: "ellos" },
            { hanzi: "都", pinyin: "dōu", meaning: "ambos, todo" },
            { hanzi: "不", pinyin: "bù", meaning: "no" },
            { hanzi: "男", pinyin: "nán", meaning: "varón" },
            { hanzi: "朋友", pinyin: "péngyou", meaning: "amigo" },
            { hanzi: "哥哥", pinyin: "gēge", meaning: "hermano mayor" },
            { hanzi: "要", pinyin: "yào", meaning: "querer" },
            { hanzi: "咖啡", pinyin: "kāfēi", meaning: "café" },
            { hanzi: "弟弟", pinyin: "dìdi", meaning: "hermano menor" },
            { hanzi: "我们", pinyin: "wǒmen", meaning: "nosotros" },
            { hanzi: "喝", pinyin: "hē", meaning: "beber" },
            { hanzi: "丁", pinyin: "Dīng", meaning: "(Apellido)" }
        ],
        sentences: [
            { hanzi: "你爸爸、妈妈好吗", pinyin: "nǐ bàba, māma hǎo ma", meaning: "¿Tus padres están bien?" },
            { hanzi: "他们都很好", pinyin: "tāmen dōu hěn hǎo", meaning: "Ellos están todos muy bien" },
            { hanzi: "我不忙", pinyin: "wǒ bù máng", meaning: "No estoy ocupado" },
            { hanzi: "你要咖啡吗", pinyin: "nǐ yào kāfēi ma", meaning: "¿Quieres café?" },
            { hanzi: "我也要咖啡", pinyin: "wǒ yě yào kāfēi", meaning: "Yo también quiero café" },
            { hanzi: "我们都喝咖啡", pinyin: "wǒmen dōu hē kāfēi", meaning: "Nosotros todos bebemos café" }
        ]
    },
    "Libro - Lección 3": {
        words: [
            { hanzi: "她", pinyin: "tā", meaning: "ella" },
            { hanzi: "是", pinyin: "shì", meaning: "ser" },
            { hanzi: "哪", pinyin: "nǎ", meaning: "cuál, de qué" },
            { hanzi: "国", pinyin: "guó", meaning: "país, nación" },
            { hanzi: "人", pinyin: "rén", meaning: "gente, persona" },
            { hanzi: "那", pinyin: "nà", meaning: "ése, aquél" },
            { hanzi: "谁", pinyin: "shéi", meaning: "quién" },
            { hanzi: "老师", pinyin: "lǎoshī", meaning: "profesor" },
            { hanzi: "中国", pinyin: "Zhōngguó", meaning: "China" },
            { hanzi: "您", pinyin: "nín", meaning: "usted" },
            { hanzi: "这", pinyin: "zhè", meaning: "éste, esto" },
            { hanzi: "外语", pinyin: "wàiyǔ", meaning: "lengua extranjera" },
            { hanzi: "医生", pinyin: "yīshēng", meaning: "médico" },
            { hanzi: "奶奶", pinyin: "nǎinai", meaning: "abuela paterna" },
            { hanzi: "外婆", pinyin: "wàipó", meaning: "abuela materna" }
        ],
        sentences: [
            { hanzi: "那是谁", pinyin: "nà shì shéi", meaning: "¿Quién es ese?" },
            { hanzi: "那是我们老师", pinyin: "nà shì wǒmen lǎoshī", meaning: "Ese es nuestro profesor" },
            { hanzi: "她是哪国人", pinyin: "tā shì nǎ guó rén", meaning: "¿De qué país es ella?" },
            { hanzi: "她是中国人", pinyin: "tā shì Zhōngguó rén", meaning: "Ella es china" },
            { hanzi: "陈老师，您好", pinyin: "Chén lǎoshī, nín hǎo", meaning: "Profesor Chen, hola (formal)" },
            { hanzi: "这是我哥哥", pinyin: "zhè shì wǒ gēge", meaning: "Este es mi hermano mayor" },
            { hanzi: "你也是老师吗", pinyin: "nǐ yě shì lǎoshī ma", meaning: "¿Tú también eres profesor?" },
            { hanzi: "我不是老师，我是医生", pinyin: "wǒ bú shì lǎoshī, wǒ shì yīshēng", meaning: "No soy profesor, soy médico" }
        ]
    },
    "HSK 1 (Básico)": {
        words: [
            { hanzi: "爱", pinyin: "ài", meaning: "amar, gustar" },
            { hanzi: "八", pinyin: "bā", meaning: "ocho" },
            { hanzi: "爸爸", pinyin: "bàba", meaning: "papá" },
            { hanzi: "杯子", pinyin: "bēizi", meaning: "vaso, taza" },
            { hanzi: "北京", pinyin: "Běijīng", meaning: "Pekín" },
            { hanzi: "本", pinyin: "běn", meaning: "clasificador (para libros)" },
            { hanzi: "不", pinyin: "bù", meaning: "no" },
            { hanzi: "不客气", pinyin: "bú kèqi", meaning: "de nada" },
            { hanzi: "菜", pinyin: "cài", meaning: "verdura, plato (comida)" },
            { hanzi: "茶", pinyin: "chá", meaning: "té" },
            { hanzi: "吃", pinyin: "chī", meaning: "comer" },
            { hanzi: "出租车", pinyin: "chūzūchē", meaning: "taxi" },
            { hanzi: "打电话", pinyin: "dǎ diànhuà", meaning: "llamar por teléfono" },
            { hanzi: "大", pinyin: "dà", meaning: "grande" },
            { hanzi: "的", pinyin: "de", meaning: "partícula posesiva" },
            { hanzi: "点", pinyin: "diǎn", meaning: "punto, en punto (hora)" },
            { hanzi: "电脑", pinyin: "diànnǎo", meaning: "computadora" },
            { hanzi: "电视", pinyin: "diànshì", meaning: "televisión" },
            { hanzi: "电影", pinyin: "diànyǐng", meaning: "película" },
            { hanzi: "东西", pinyin: "dōngxi", meaning: "cosa" },
            { hanzi: "都", pinyin: "dōu", meaning: "todos, ambos" },
            { hanzi: "读", pinyin: "dú", meaning: "leer" },
            { hanzi: "对不起", pinyin: "duìbuqǐ", meaning: "lo siento, perdón" },
            { hanzi: "多", pinyin: "duō", meaning: "mucho, más" },
            { hanzi: "多少", pinyin: "duōshao", meaning: "cuánto" },
            { hanzi: "儿子", pinyin: "érzi", meaning: "hijo" },
            { hanzi: "二", pinyin: "èr", meaning: "dos" },
            { hanzi: "饭馆", pinyin: "fànguǎn", meaning: "restaurante" },
            { hanzi: "飞机", pinyin: "fēijī", meaning: "avión" },
            { hanzi: "分钟", pinyin: "fēnzhōng", meaning: "minuto" },
            { hanzi: "高兴", pinyin: "gāoxìng", meaning: "feliz, contento" },
            { hanzi: "个", pinyin: "gè", meaning: "clasificador general" },
            { hanzi: "工作", pinyin: "gōngzuò", meaning: "trabajo, trabajar" },
            { hanzi: "狗", pinyin: "gǒu", meaning: "perro" },
            { hanzi: "汉语", pinyin: "Hànyǔ", meaning: "idioma chino" },
            { hanzi: "好", pinyin: "hǎo", meaning: "bien, bueno" },
            { hanzi: "号", pinyin: "hào", meaning: "día (fecha), número" },
            { hanzi: "喝", pinyin: "hē", meaning: "beber" },
            { hanzi: "和", pinyin: "hé", meaning: "y, con" },
            { hanzi: "很", pinyin: "hěn", meaning: "muy" },
            { hanzi: "后面", pinyin: "hòumiàn", meaning: "atrás, detrás" },
            { hanzi: "回", pinyin: "huí", meaning: "volver, regresar" },
            { hanzi: "会", pinyin: "huì", meaning: "saber (hacer algo), poder" },
            { hanzi: "几", pinyin: "jǐ", meaning: "cuántos (menos de 10)" },
            { hanzi: "家", pinyin: "jiā", meaning: "casa, familia" },
            { hanzi: "叫", pinyin: "jiào", meaning: "llamarse, gritar" },
            { hanzi: "今天", pinyin: "jīntiān", meaning: "hoy" },
            { hanzi: "九", pinyin: "jiǔ", meaning: "nueve" },
            { hanzi: "开", pinyin: "kāi", meaning: "abrir, conducir" },
            { hanzi: "看", pinyin: "kàn", meaning: "mirar, ver, leer" },
            { hanzi: "看见", pinyin: "kànjiàn", meaning: "ver, divisar" },
            { hanzi: "块", pinyin: "kuài", meaning: "clasificador para dinero/pedazos" },
            { hanzi: "来", pinyin: "lái", meaning: "venir" },
            { hanzi: "老师", pinyin: "lǎoshī", meaning: "profesor" },
            { hanzi: "了", pinyin: "le", meaning: "partícula de cambio de estado" },
            { hanzi: "冷", pinyin: "lěng", meaning: "frío" },
            { hanzi: "里", pinyin: "lǐ", meaning: "dentro" },
            { hanzi: "零", pinyin: "líng", meaning: "cero" },
            { hanzi: "六", pinyin: "liù", meaning: "seis" },
            { hanzi: "妈妈", pinyin: "māma", meaning: "mamá" },
            { hanzi: "吗", pinyin: "ma", meaning: "partícula interrogativa" },
            { hanzi: "买", pinyin: "mǎi", meaning: "comprar" },
            { hanzi: "猫", pinyin: "māo", meaning: "gato" },
            { hanzi: "没", pinyin: "méi", meaning: "no (tener, haber)" },
            { hanzi: "没关系", pinyin: "méi guānxi", meaning: "no importa" },
            { hanzi: "米饭", pinyin: "mǐfàn", meaning: "arroz cocido" },
            { hanzi: "明天", pinyin: "míngtiān", meaning: "mañana (día)" },
            { hanzi: "名字", pinyin: "míngzi", meaning: "nombre" },
            { hanzi: "哪", pinyin: "nǎ", meaning: "cuál" },
            { hanzi: "那", pinyin: "nà", meaning: "ese, aquel" },
            { hanzi: "呢", pinyin: "ne", meaning: "partícula modal" },
            { hanzi: "能", pinyin: "néng", meaning: "poder (capacidad)" },
            { hanzi: "你", pinyin: "nǐ", meaning: "tú" },
            { hanzi: "年", pinyin: "nián", meaning: "año" },
            { hanzi: "女儿", pinyin: "nǚér", meaning: "hija" },
            { hanzi: "朋友", pinyin: "péngyou", meaning: "amigo" },
            { hanzi: "漂亮", pinyin: "piàoliang", meaning: "bonito, hermoso" },
            { hanzi: "苹果", pinyin: "píngguǒ", meaning: "manzana" },
            { hanzi: "七", pinyin: "qī", meaning: "siete" },
            { hanzi: "钱", pinyin: "qián", meaning: "dinero" },
            { hanzi: "前面", pinyin: "qiánmiàn", meaning: "adelante, enfrente" },
            { hanzi: "请", pinyin: "qǐng", meaning: "por favor, invitar" },
            { hanzi: "去", pinyin: "qù", meaning: "ir" },
            { hanzi: "热", pinyin: "rè", meaning: "calor, caliente" },
            { hanzi: "人", pinyin: "rén", meaning: "persona" },
            { hanzi: "认识", pinyin: "rènshi", meaning: "conocer (a alguien)" },
            { hanzi: "三", pinyin: "sān", meaning: "tres" },
            { hanzi: "商店", pinyin: "shāngdiàn", meaning: "tienda" },
            { hanzi: "上", pinyin: "shàng", meaning: "arriba, subir" },
            { hanzi: "上午", pinyin: "shàngwǔ", meaning: "mañana (antes del mediodía)" },
            { hanzi: "少", pinyin: "shǎo", meaning: "poco" },
            { hanzi: "谁", pinyin: "shéi", meaning: "quién" },
            { hanzi: "什么", pinyin: "shénme", meaning: "qué" },
            { hanzi: "十", pinyin: "shí", meaning: "diez" },
            { hanzi: "时候", pinyin: "shíhou", meaning: "momento, tiempo" },
            { hanzi: "是", pinyin: "shì", meaning: "ser" },
            { hanzi: "书", pinyin: "shū", meaning: "libro" },
            { hanzi: "水", pinyin: "shuǐ", meaning: "agua" },
            { hanzi: "水果", pinyin: "shuǐguǒ", meaning: "fruta" },
            { hanzi: "睡觉", pinyin: "shuìjiào", meaning: "dormir" },
            { hanzi: "说话", pinyin: "shuōhuà", meaning: "hablar" },
            { hanzi: "四", pinyin: "sì", meaning: "cuatro" },
            { hanzi: "岁", pinyin: "suì", meaning: "años de edad" },
            { hanzi: "他", pinyin: "tā", meaning: "él" },
            { hanzi: "她", pinyin: "tā", meaning: "ella" },
            { hanzi: "太", pinyin: "tài", meaning: "demasiado" },
            { hanzi: "天气", pinyin: "tiānqì", meaning: "clima, tiempo" },
            { hanzi: "听", pinyin: "tīng", meaning: "escuchar" },
            { hanzi: "同学", pinyin: "tóngxué", meaning: "compañero de clase" },
            { hanzi: "喂", pinyin: "wéi", meaning: "aló (al teléfono)" },
            { hanzi: "我", pinyin: "wǒ", meaning: "yo" },
            { hanzi: "我们", pinyin: "wǒmen", meaning: "nosotros" },
            { hanzi: "五", pinyin: "wǔ", meaning: "cinco" },
            { hanzi: "喜欢", pinyin: "xǐhuan", meaning: "gustar" },
            { hanzi: "下", pinyin: "xià", meaning: "abajo, bajar" },
            { hanzi: "下午", pinyin: "xiàwǔ", meaning: "tarde (después del mediodía)" },
            { hanzi: "下雨", pinyin: "xiàyǔ", meaning: "llover" },
            { hanzi: "先生", pinyin: "xiānsheng", meaning: "señor" },
            { hanzi: "现在", pinyin: "xiànzài", meaning: "ahora" },
            { hanzi: "想", pinyin: "xiǎng", meaning: "pensar, querer" },
            { hanzi: "小", pinyin: "xiǎo", meaning: "pequeño" },
            { hanzi: "小姐", pinyin: "xiǎojiě", meaning: "señorita" },
            { hanzi: "些", pinyin: "xiē", meaning: "algunos" },
            { hanzi: "写", pinyin: "xiě", meaning: "escribir" },
            { hanzi: "谢谢", pinyin: "xièxie", meaning: "gracias" },
            { hanzi: "星期", pinyin: "xīngqī", meaning: "semana" },
            { hanzi: "学生", pinyin: "xuésheng", meaning: "estudiante" },
            { hanzi: "学习", pinyin: "xuéxí", meaning: "estudiar" },
            { hanzi: "学校", pinyin: "xuéxiào", meaning: "escuela" },
            { hanzi: "一", pinyin: "yī", meaning: "uno" },
            { hanzi: "衣服", pinyin: "yīfu", meaning: "ropa" },
            { hanzi: "医生", pinyin: "yīshēng", meaning: "médico" },
            { hanzi: "医院", pinyin: "yīyuàn", meaning: "hospital" },
            { hanzi: "椅子", pinyin: "yǐzi", meaning: "silla" },
            { hanzi: "有", pinyin: "yǒu", meaning: "tener, haber" },
            { hanzi: "月", pinyin: "yuè", meaning: "mes" },
            { hanzi: "再见", pinyin: "zàijiàn", meaning: "adiós" },
            { hanzi: "在", pinyin: "zài", meaning: "estar, en" },
            { hanzi: "怎么", pinyin: "zěnme", meaning: "cómo" },
            { hanzi: "怎么样", pinyin: "zěnmeyàng", meaning: "qué tal" },
            { hanzi: "这", pinyin: "zhè", meaning: "este, esto" },
            { hanzi: "中国", pinyin: "Zhōngguó", meaning: "China" },
            { hanzi: "中午", pinyin: "zhōngwǔ", meaning: "mediodía" },
            { hanzi: "住", pinyin: "zhù", meaning: "vivir, residir" },
            { hanzi: "桌子", pinyin: "zhuōzi", meaning: "mesa" },
            { hanzi: "字", pinyin: "zì", meaning: "carácter" },
            { hanzi: "昨天", pinyin: "zuótiān", meaning: "ayer" },
            { hanzi: "坐", pinyin: "zuò", meaning: "sentarse" },
            { hanzi: "做", pinyin: "zuò", meaning: "hacer" }
        ],
        sentences: [
            { hanzi: "你好吗", pinyin: "nǐ hǎo ma", meaning: "¿Cómo estás?" },
            { hanzi: "我爱你", pinyin: "wǒ ài nǐ", meaning: "Te amo" },
            { hanzi: "他喝茶", pinyin: "tā hē chá", meaning: "Él bebe té" },
            { hanzi: "我去北京", pinyin: "wǒ qù běijīng", meaning: "Voy a Pekín" },
            { hanzi: "你叫什么名字", pinyin: "nǐ jiào shénme míngzi", meaning: "¿Cómo te llamas?" },
            { hanzi: "我很高兴认识你", pinyin: "wǒ hěn gāoxìng rènshi nǐ", meaning: "Estoy muy feliz de conocerte" },
            { hanzi: "谢谢你", pinyin: "xièxie nǐ", meaning: "Gracias" },
            { hanzi: "对不起", pinyin: "duìbuqǐ", meaning: "Lo siento" },
            { hanzi: "没关系", pinyin: "méi guānxi", meaning: "No pasa nada" },
            { hanzi: "这是我的书", pinyin: "zhè shì wǒ de shū", meaning: "Este es mi libro" },
            { hanzi: "那个人是谁", pinyin: "nà ge rén shì shéi", meaning: "¿Quién es esa persona?" },
            { hanzi: "你是哪国人", pinyin: "nǐ shì nǎ guó rén", meaning: "¿De qué país eres?" },
            { hanzi: "我是中国人", pinyin: "wǒ shì zhōngguó rén", meaning: "Soy chino" },
            { hanzi: "他会说汉语", pinyin: "tā huì shuō hànyǔ", meaning: "Él sabe hablar chino" },
            { hanzi: "我们去看电影", pinyin: "wǒmen qù kàn diànyǐng", meaning: "Vamos a ver una película" },
            { hanzi: "你想吃什么", pinyin: "nǐ xiǎng chī shénme", meaning: "¿Qué quieres comer?" },
            { hanzi: "我不吃米饭", pinyin: "wǒ bù chī mǐfàn", meaning: "No como arroz" },
            { hanzi: "今天天气很好", pinyin: "jīntiān tiānqì hěn hǎo", meaning: "Hoy el clima es muy bueno" },
            { hanzi: "明天会下雨吗", pinyin: "míngtiān huì xiàyǔ ma", meaning: "¿Mañana lloverá?" },
            { hanzi: "现在几点", pinyin: "xiànzài jǐ diǎn", meaning: "¿Qué hora es ahora?" },
            { hanzi: "我妈妈在医院工作", pinyin: "wǒ māma zài yīyuàn gōngzuò", meaning: "Mi mamá trabaja en el hospital" },
            { hanzi: "你的猫很漂亮", pinyin: "nǐ de māo hěn piàoliang", meaning: "Tu gato es muy bonito" }
        ]
    },
    "Libro - Lección 4": {
        words: [
            { hanzi: "认识", pinyin: "rènshi", meaning: "conocer (a alguien)" },
            { hanzi: "高兴", pinyin: "gāoxìng", meaning: "contento, encantado" },
            { hanzi: "可以", pinyin: "kěyǐ", meaning: "poder" },
            { hanzi: "进来", pinyin: "jìnlái", meaning: "entrar" },
            { hanzi: "进", pinyin: "jìn", meaning: "entrar" },
            { hanzi: "来", pinyin: "lái", meaning: "venir" },
            { hanzi: "请", pinyin: "qǐng", meaning: "por favor" },
            { hanzi: "记者", pinyin: "jìzhě", meaning: "periodista" },
            { hanzi: "请问", pinyin: "qǐngwèn", meaning: "¿Podría preguntar...?" },
            { hanzi: "问", pinyin: "wèn", meaning: "preguntar" },
            { hanzi: "贵姓", pinyin: "guìxìng", meaning: "¿Cómo se llama? (apellido formal)" },
            { hanzi: "姓", pinyin: "xìng", meaning: "apellido, apellidarse" },
            { hanzi: "叫", pinyin: "jiào", meaning: "llamar(se)" },
            { hanzi: "先生", pinyin: "xiānsheng", meaning: "señor" },
            { hanzi: "杨", pinyin: "Yáng", meaning: "Yang (apellido)" },
            { hanzi: "语言", pinyin: "yǔyán", meaning: "lengua, idioma" },
            { hanzi: "学院", pinyin: "xuéyuàn", meaning: "instituto, universidad" },
            { hanzi: "的", pinyin: "de", meaning: "partícula posesiva" },
            { hanzi: "学生", pinyin: "xuésheng", meaning: "estudiante" },
            { hanzi: "什么", pinyin: "shénme", meaning: "qué" },
            { hanzi: "学习", pinyin: "xuéxí", meaning: "estudiar, aprender" },
            { hanzi: "汉语", pinyin: "Hànyǔ", meaning: "idioma chino" },
            { hanzi: "英国", pinyin: "Yīngguó", meaning: "Inglaterra, Gran Bretaña" },
            { hanzi: "加拿大", pinyin: "Jiānádà", meaning: "Canadá" },
            { hanzi: "美国", pinyin: "Měiguó", meaning: "Estados Unidos" },
            { hanzi: "马大为", pinyin: "Mǎ Dàwéi", meaning: "(Nombre)" }
        ],
        sentences: [
            { hanzi: "可以进来吗", pinyin: "kěyǐ jìnlaimai", meaning: "¿Puedo entrar?" },
            { hanzi: "请进", pinyin: "qǐng jìn", meaning: "¡Pase, por favor!" },
            { hanzi: "他是记者", pinyin: "tā shì jìzhě", meaning: "Él es periodista" },
            { hanzi: "请问您贵姓", pinyin: "qǐngwèn, nín guìxìng", meaning: "Disculpe, ¿cuál es su apellido?" },
            { hanzi: "我姓陆叫陆雨平", pinyin: "wǒ xìng Lù, jiào Lù Yǔpíng", meaning: "Me apellido Lu, me llamo Lu Yuping" },
            { hanzi: "认识你很高兴", pinyin: "rènshi nǐ hěn gāoxìng", meaning: "Encantado de conocerte" },
            { hanzi: "我是语言学院的学生", pinyin: "wǒ shì yǔyán xuéyuàn de xuésheng", meaning: "Soy estudiante del instituto de idiomas" },
            { hanzi: "你姓什么", pinyin: "nǐ xìng shénme", meaning: "¿Cuál es tu apellido?" },
            { hanzi: "你是加拿大人吗", pinyin: "nǐ shì jiānádà rén ma", meaning: "¿Eres canadiense?" },
            { hanzi: "我不是加拿大人", pinyin: "wǒ bú shì jiānádà rén", meaning: "No soy canadiense" },
            { hanzi: "我学习汉语", pinyin: "wǒ xuéxí hànyǔ", meaning: "Estudio idioma chino" }
        ]
    },
    "Libro - Lección 5": {
        words: [
            { hanzi: "餐厅", pinyin: "cāntīng", meaning: "comedor" },
            { hanzi: "在", pinyin: "zài", meaning: "estar (aquí, allí)" },
            { hanzi: "哪儿", pinyin: "nǎr", meaning: "dónde" },
            { hanzi: "宿舍", pinyin: "sùshè", meaning: "dormitorio" },
            { hanzi: "女", pinyin: "nǚ", meaning: "mujer" },
            { hanzi: "坐", pinyin: "zuò", meaning: "sentarse" },
            { hanzi: "谢谢", pinyin: "xièxie", meaning: "dar las gracias" },
            { hanzi: "对不起", pinyin: "duìbuqǐ", meaning: "lo siento, perdón" },
            { hanzi: "知道", pinyin: "zhīdào", meaning: "saber" },
            { hanzi: "没关系", pinyin: "méi guānxi", meaning: "no importa, da igual" },
            { hanzi: "再见", pinyin: "zàijiàn", meaning: "¡Hasta luego!" },
            { hanzi: "再", pinyin: "zài", meaning: "otra vez" },
            { hanzi: "王小云", pinyin: "Wáng Xiǎoyún", meaning: "(Nombre)" },
            { hanzi: "小姐", pinyin: "xiǎojiě", meaning: "señorita" },
            { hanzi: "层", pinyin: "céng", meaning: "piso, planta" },
            { hanzi: "二", pinyin: "èr", meaning: "dos" },
            { hanzi: "〇", pinyin: "líng", meaning: "cero (0)" },
            { hanzi: "四", pinyin: "sì", meaning: "cuatro" },
            { hanzi: "号", pinyin: "hào", meaning: "número" },
            { hanzi: "不用谢", pinyin: "búyòng xiè", meaning: "de nada (no hay de qué)" }
        ],
        sentences: [
            { hanzi: "餐厅在哪儿", pinyin: "cāntīng zài nǎr", meaning: "¿Dónde está el comedor?" },
            { hanzi: "这是王小云的宿舍吗", pinyin: "zhè shì wáng xiǎoyún de sùshè ma", meaning: "¿Es este el dormitorio de Wang Xiaoyun?" },
            { hanzi: "请坐", pinyin: "qǐng zuò", meaning: "Por favor, siéntese" },
            { hanzi: "王小云在吗", pinyin: "wáng xiǎoyún zài ma", meaning: "¿Está Wang Xiaoyun?" },
            { hanzi: "她不在", pinyin: "tā bú zài", meaning: "Ella no está" },
            { hanzi: "她在哪儿", pinyin: "tā zài nǎr", meaning: "¿Dónde está ella?" },
            { hanzi: "我不知道", pinyin: "wǒ bù zhīdào", meaning: "No lo sé" },
            { hanzi: "在二层二〇四号", pinyin: "zài èr céng èr líng sì hào", meaning: "En el segundo piso, número 204" },
            { hanzi: "不用谢", pinyin: "búyòng xiè", meaning: "De nada" }
        ]
    },
    "Libro - Lección 6": {
        words: [
            { hanzi: "去", pinyin: "qù", meaning: "ir" },
            { hanzi: "游泳", pinyin: "yóuyǒng", meaning: "nadar" },
            { hanzi: "昨天", pinyin: "zuótiān", meaning: "ayer" },
            { hanzi: "京剧", pinyin: "jīngjù", meaning: "Ópera de Pekín" },
            { hanzi: "怎么样", pinyin: "zěnmeyàng", meaning: "¿qué tal?" },
            { hanzi: "有意思", pinyin: "yǒu yìsi", meaning: "interesante" },
            { hanzi: "今天", pinyin: "jīntiān", meaning: "hoy" },
            { hanzi: "天", pinyin: "tiān", meaning: "día" },
            { hanzi: "天气", pinyin: "tiānqì", meaning: "tiempo atmosférico" },
            { hanzi: "太", pinyin: "tài", meaning: "demasiado" },
            { hanzi: "什么", pinyin: "shénme", meaning: "qué" },
            { hanzi: "时候", pinyin: "shíhou", meaning: "tiempo, momento" },
            { hanzi: "现在", pinyin: "xiànzài", meaning: "ahora" },
            { hanzi: "明天", pinyin: "míngtiān", meaning: "mañana" },
            { hanzi: "有", pinyin: "yǒu", meaning: "tener" },
            { hanzi: "时间", pinyin: "shíjiān", meaning: "tiempo" },
            { hanzi: "说", pinyin: "shuō", meaning: "hablar" },
            { hanzi: "遍", pinyin: "biàn", meaning: "vez (número de veces de una acción)" },
            { hanzi: "打球", pinyin: "dǎ qiú", meaning: "jugar a la pelota" },
            { hanzi: "打", pinyin: "dǎ", meaning: "jugar" },
            { hanzi: "球", pinyin: "qiú", meaning: "pelota" },
            { hanzi: "抱歉", pinyin: "bàoqiàn", meaning: "lo siento" },
            { hanzi: "忙", pinyin: "máng", meaning: "ocupado" },
            { hanzi: "恐怕", pinyin: "kǒngpà", meaning: "quizás, temer que" },
            { hanzi: "行", pinyin: "xíng", meaning: "estar bien, posible" },
            { hanzi: "你们", pinyin: "nǐmen", meaning: "vosotros, ustedes" }
        ],
        sentences: [
            { hanzi: "昨天的京剧怎么样", pinyin: "zuótiān de jīngjù zěnmeyàng", meaning: "¿Qué tal la ópera de Pekín de ayer?" },
            { hanzi: "很有意思", pinyin: "hěn yǒu yìsi", meaning: "Muy interesante" },
            { hanzi: "今天天气很好", pinyin: "jīntiān tiānqì hěn hǎo", meaning: "Hoy hace muy buen tiempo" },
            { hanzi: "我们去游泳好吗", pinyin: "wǒmen qù yóuyǒng, hǎo ma", meaning: "Vamos a nadar, ¿de acuerdo?" },
            { hanzi: "太好了", pinyin: "tài hǎo le", meaning: "¡Fantástico! / ¡Demasiado bueno!" },
            { hanzi: "什么时候去", pinyin: "shénme shíhou qù", meaning: "¿Cuándo vamos?" },
            { hanzi: "现在去可以吗", pinyin: "xiànzài qù, kěyǐ ma", meaning: "Vamos ahora, ¿se puede?" },
            { hanzi: "明天您有时间吗", pinyin: "míngtiān nín yǒu shíjiān ma", meaning: "¿Mañana tiene tiempo?" },
            { hanzi: "请再说一遍", pinyin: "qǐng zài shuō yí biàn", meaning: "Por favor, dilo otra vez" },
            { hanzi: "我们去打球好吗", pinyin: "wǒmen qù dǎ qiú, hǎo ma", meaning: "Vamos a jugar a la pelota, ¿de acuerdo?" },
            { hanzi: "很抱歉", pinyin: "hěn bàoqiàn", meaning: "Lo siento mucho" },
            { hanzi: "明天我很忙", pinyin: "míngtiān wǒ hěn máng", meaning: "Mañana estoy muy ocupado" },
            { hanzi: "恐怕不行", pinyin: "kǒngpà bù xíng", meaning: "Me temo que no se puede" }
        ]
    }
};
